mysociety/mapit

bin/install-as-user
bin/site-specific-install.sh

As described here:
https://docs.djangoproject.com/en/1.6/ref/contrib/gis/install/postgis/#creating-a-spatial-database-with-postgis-2-0-and-postgresql-9-1
... creating a PostGIS database should be done with
"CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;"
where PostGIS and PostgreSQL are late enough versions, rather
than the script to create a template_postgis template.
The only supported distribution where we have these versions is
currently Ubuntu trusty.

Use "CREATE EXTENSION postgis; ..." on Ubuntu trusty

---

.travis.yml
mapit/iterables.py
mapit/middleware/__init__.py
mapit/middleware/gzip.py
mapit/models.py
mapit/shortcuts.py
mapit/templates/mapit/areas.html
mapit/templates/mapit/areas_item.html
mapit/templates/mapit/data.html
mapit/tests/test_middleware.py
mapit/tests/test_views.py
mapit/tests/utils.py
mapit/views/areas.py
mapit/views/postcodes.py
mapit_gb/tests.py
mapit_global/countries.py
project/settings.py

When we start, we have an iterable `QuerySet`. So this changes `add_codes` to be iterable, passes an `iterdict` [1] rather than a `dict` to `output_json`, changes `output_json` to use a `StreamingHttpResponse` by default, and updates the callback middleware to work with streaming or non-streaming responses. This hopefully reduces memory usage for one particular request from c. 2Gb to 200Mb. Similarly for `output_html`, we keep everything as an iterable, doing something horrible with a template in order to put our iteration in the middle.
[1] An `iterdict` is a `dict` subclass that does nothing but provide an iterable for `items`/`iteritems`, in order so that the `json` package will think it's a dictionary, iterate over it and output an iterator. Otherwise we'd need to load everything into …

Stream JSON responses

---

MANIFEST.in
mapit_gb/templates/mapit/api/area-example-related.html
mapit_gb/templates/mapit/api/area-example.html
mapit_gb/templates/mapit/api/areas-examples.html
mapit_gb/templates/mapit/api/point-example-nearest.html
mapit_gb/templates/mapit/api/point-example.html
mapit_gb/templates/mapit/api/postcode-example-partial.html
mapit_gb/templates/mapit/api/postcode-example.html
mapit_global/templates/mapit/api/area-example-related.html
mapit_global/templates/mapit/api/area-example.html
mapit_global/templates/mapit/api/areas-examples.html
mapit_global/templates/mapit/api/point-example-nearest.html
mapit_global/templates/mapit/api/point-example.html
mapit_no/templates/mapit/api/area-example-related.html
mapit_no/templates/mapit/api/area-example.html
mapit_no/templates/mapit/api/areas-examples.html
mapit_no/templates/mapit/api/point-example-nearest.html
mapit_no/templates/mapit/api/point-example.html
mapit_no/templates/mapit/api/postcode-example-partial.html
mapit_no/templates/mapit/api/postcode-example.html
mapit_za/templates/mapit/api/point-example.html

These were left out of the package by mistake, meaning you couldn't
use them from a different project when you installed django-mapit,
which is a shame.
This adds recursive-include statements for all of the current country apps.

Add country-specific templates to MANIFEST.in

---

mapit/management/commands/mapit_generation_raise_on_current_areas.py
mapit/tests/test_generation_commands.py

This is useful if you've created a new generation for a new data
import, but there are existing areas in the database that should
still remain active after you've activated your new generation.
After creating the new inactive generation you can run this command
to raise the generation_high of any areas who have a generation_high
set to the current (i.e. most recent active) generation so that
they're the newly created generation.
You could do this in the Django shell, but this seems like a safer
way of doing this.

Add a command to raise the generation_high on current areas

---

mapit_global/management/commands/mapit_global_import.py

The xml.sax module in python2 prior to 2.7.4 cannot handle a Unicode
filename (this was Python issue https://bugs.python.org/issue11159).
Make sure that we pass a str to xml.sax, which should be fine in any
version of python. Fixes #206.

Fix bug parsing KML with Unicode filename.

---

mapit/tests/test_import_commands.py

When running the mapit tests as a group, something is leaving GDAL drivers
open/registered (I'm not sure of the terminology), but only Raster ones.
Django's Driver class checks for the existence of drivers before registering
new ones, but it assumes that if any exist, they all do: https://github.com/django/django/blob/b35adb0909b25a7dafc9212ddedfbf9b29dc05b8/django/contrib/gis/gdal/driver.py#L81-L83
In these tests that was not the case, so calls to the Vector driver resulted
in a pointer error. This commit provides a temporary workaround which force-
registers a driver (if none already exist) before the test runs.

Fix GDAL error in mapit_import tests

---

mapit/management/commands/mapit_import_postal_codes.py
mapit_gb/management/commands/mapit_UK_import_nspd_ni.py

Django 1.6 deprecated `transaction.commit_manually` and Django 1.8 dropped
it entirely so we have to use modern transactions.  There's no direct upgrade
path from the old api to the modern one so just wrapping the relevant bit in
`transaction.atomic` seems reasonable.

Use modern transactions in mapit_UK_import_nspd_ni

---

mapit_gb/controls/2009-10.py
mapit_gb/controls/2010-05.py
mapit_gb/controls/2010-10.py
mapit_gb/controls/2011-05.py
mapit_gb/controls/2011-10.py
mapit_gb/controls/2012-05.py
mapit_gb/controls/2012-10.py
mapit_gb/controls/2013-05.py
mapit_gb/controls/2013-10.py
mapit_gb/controls/2014-05.py
mapit_gb/controls/2014-10.py
mapit_gb/controls/2015-05.py
mapit_gb/controls/2015-10.py
mapit_gb/controls/first-gss.py
mapit_gb/controls/first-ons.py
mapit_gb/controls/possible-future.py
mapit_gb/management/commands/mapit_UK_import_boundary_line.py

Couple of issues to work around this time:

October 2015 Boundary-Line

---

conf/general.yml-example
project/settings.py

Offering this as it's a change we've made to our fork.
In GOV.UK we want to specify different email subject lines for MapIt emails in each environment.  This change allows the EMAIL_SUBJECT_PREFIX to be set in general.yml.
The space after the closing ']' in the example is intentional in order to format the full email subject nicely when it includes following text.

Allow overriding of email subject prefix

---

mapit/urls.py
mapit/views/areas.py
mapit_gb/countries.py

If you've included MapIt in another Django project, e.g. with:
urlpatterns += patterns('',
(r'^mapit/', include('mapit.urls')),
)
... then some of the views that returned a redirect to a URL
constructed with string formatting would redirect to a path
that didn't include the 'mapit/' prefix.  If these paths are
constructed with reverse() instead, it works properly.
This also introduces some new URL pattern names, so the URL
patterns can be referred to more concisely.

Use reverse so more redirects work when MapIt is mounted on a subpath

---

.gitignore
CONTRIBUTING.md
VagrantFile
conf/sysvinit.example

I needed to get mapit.mysociety.org and global.mapit.mysociety.org running on my Mac today, to do https://github.com/mysociety/mapit.mysociety.org/issues/17.
Installing everything (postgres, postgis, gdal, etc) onto my Mac seemed like a right pain, so I borrowed the VagrantFile that @stevenday wrote for [the mapit.mysociety.org repo](https://github.com/mysociety/mapit.mysociety.org/commit/ebcd03a37f851fa4cb037476cfa12337f7c8a429#diff-23b6f443c01ea2efcb4f36eedfea9089) and tweaked it to work with my copy of mapit.
Have tested it on my Mac running OS X 10.10.4, Vagrant 1.7.4, and VirtualBox 5.0.10. Mostly works, although I get an error about `mailcatcher` not existing, at the end of the first `vagrant up`.

Add VagrantFile and setup instructions for local development

---

bin/install-as-user
bin/site-specific-install.sh

The script hardcoded a check for trusty as a proxy for PostGIS 2.
Instead, look up the postgis package version installed and use that.

Support jessie/xenial in install scripts.

---

mapit/views/areas.py

If it is done too early, at module import, it triggers a bug in Django whereby the DataSource drivers aren't registered and an import fails.
(I wondered if it was simpler to force a DataSource registration in e.g. manage.py, but as this is the only place using osgeo.gdal, it seemed to make sense to put it there, and nothing front-end uses DataSource anyway. Happy to do it differently if others prefer.)

Only try and set gdal exceptions on first use.

---

mapit_gb/countries.py
setup.py

This is much quicker, and includes a missing "P" in the third character list. Thanks to Andy Gimblett for suggesting these changes to the https://github.com/mysociety/uk-postcode-utils package.

[UK] Improved postcode validation.

---

mapit/models.py
mapit/tests/test_names.py
mapit_gb/management/commands/mapit_UK_time_lookups.py
mapit_global/management/commands/mapit_global_import.py
project/wsgi_monitor.py

Fix display of Geometry object in admin.

---

mapit/templates/mapit/analytics.html
mapit/templates/mapit/base.html

Putting the analytics code into a partial makes it easier for individual cobrands (eg: MapIt UK) to override their analytics tracking setup – for example, to upgrade to Universal Analytics, or to define custom dimensions/metrics before the pageview event is sent.

Split analytics code into partial for easy overrides

---

mapit/templates/mapit/area.html
mapit/templates/mapit/postcode.html

Useful for cobrands that want to display a small amount of custom data, or a message to users, without overriding the whole template.
(We’re using this in MapIt UK to display a message about business users and paid plans.)

Block for extra content in area/postcode info

---

mapit/urls.py
mapit/utils.py
mapit/views/areas.py

This should prevent errors where a submission such as '53.8487,2.9295.'
was matched and then could not be reversed.

Improve and sync number regex in URL/point form.

---

bin/get-boundaries-by-admin-level.py

As the political_division was entered as a bytestring, not a Unicode string, it did not match against the returned data.

Find French legislative boundaries.

---

mapit_global/fixtures/global.json
mapit_global/management/commands/mapit_global_import.py

This adds the `ref` attribute from OSM, if present, as a new kind of `Code` when performing a global import from KML files.
This is part of the work adding Mapit as a source of area data in EveryPolitician - https://github.com/everypolitician/everypolitician/issues/595. This addition should make matching between Mapit/OSM and Wikidata simpler, which in turn will make it easier to reconcile the data between the two in EveryPolitician.
For a full explanation, see @mhl's comment - https://github.com/everypolitician/everypolitician/issues/595#issuecomment-288382893.

Add OSM ref attribute as part of global import

---

MANIFEST.in

Add all directories to the packaged version, exclude any Python cache files.
Fixes #289

Add missing files from packaged django-mapit

---

mapit/management/commands/mapit_import_postal_codes.py
mapit/models.py
mapit/templates/mapit/postcode.html
mapit/tests/test_names.py
mapit/tests/test_views.py
mapit_gb/countries.py
mapit_gb/tests.py

If the application is running on a server with GDAL 1.9 (and maybe 1.8),
its OSGB co-ordinate transformation can be up to a few metres out. As we
use the transformation by the database when saving new coordinates, also
use it when fetching so we can match and display accurate information.

[UK] Use database for co-ordinate transformation.

---

mapit_international/management/commands/mapit_international_add_fb_ids.py

In politician data we're producing for another project, we need IDs that
are unique across multiple area types - this command adds those for
French areas, so we can test point lookups.

Add new IDs to French areas in International MapIt

---

.travis.yml

The explict installation of PostgreSQL 9.6 and PostGIS 2.3 is due to
this problem with the new Travis container-based trusty build
environment:
https://github.com/travis-ci/travis-ci/issues/6972

Ensure PostGIS works in the new default Travis build environment

---

mapit/tests/test_views.py
mapit/views/postcodes.py
setup.cfg

Something about the recent move to Postgres 9.6 and PostGIS 2.3 caused
the /nearest query to take much longer than 10 seconds to complete.
This commit updates the query to use the ‘<->’ centroid distance operator
instead, which makes better use of the geoindex and is much faster to
execute.
Handily the work @dracos did to introduce the TrigramDistance function
into Django 1.10 was easily adapted for this purpose, as it uses the
same operator.
This needs a bit of tidying and refactoring before merging really.

First stab at fixing /nearest

---

mapit/templates/mapit/api/areas.html
mapit/templates/mapit/api/point.html
mapit/tests/test_query_args.py
mapit/views/areas.py

This change means that you can add `?country=E` (say) to queries for
multiple areas to restrict the results to those areas that have a
Country with code `E`.
This should be particularly helpful for global.mapit.mysociety.org
if we set an appropriate Country for each Area, since one is almost
always interested in results from a particular country.
Fixes #55

Add support for a 'country' filter in query parameters

---

mapit/shortcuts.py
mapit/templates/mapit/area.html
mapit/templates/mapit/areas_item.html
mapit/templates/mapit/data.html
mapit/templates/mapit/map/init.html
mapit/templates/mapit/map/json.html
mapit/templates/mapit/postcode.html
mapit/urls.py
mapit/views/areas.py

This works for any list page (children/point/areas by name/etc). It restricts itself to the first 200 areas of the list if there are more.
As list pages are output streamed, it has to collect the IDs as it goes and do the map at the end; I think this should be okay for any sensible page.
Fixes #307

 Add .map.html endpoint to show map of areas

---

mapit/templates/mapit/base.html
mapit/templates/mapit/index.html
mapit/templates/mapit/postcode.html

Leaflet creates a div, reads its background image path and tries to remove the `url("` and `marker-icon.png")` from it, but because deployment has rewritten marker-icon.png to marker-icon.123456.png it doesn't work and makes a broken image. So we set it manually - it would be good not to hardcode `/static/` I guess, but is anyone going to use anything different really?

Fix marker icon

---

mapit/geometryserialiser.py
mapit/tests/test_views.py

This is far quicker than the GEOSGeometry outputs.
For one particular complicated boundary, 12 seconds down to 1 second.

Switch to OGR kml/geojson generation.

---

mapit/views/areas.py

There’s no need for POST protection on this URL as it
doesn’t modify any data or reveal anything specific to
a logged-in user.

Make POST to /areas CSRF-exempt

---

mapit/models.py
mapit/views/areas.py

iterator() and prefetch() can't be used together, so the prefetch of many-many
countries is not happening in area lists, causing a slowdown if many areas are
to be returned. Instead, as we already do with codes, we manually fetch all of
the relevant countries from the join table and store them on the model objects
as we iterate through them.

Manually prefetch any matching many-many countries

---

mapit/migrations/0001_initial.py
mapit/models.py

Currently under Python 3 - Django wants to create new migration files to fix the change in description from a byte string to unicode string.
This PR updates models.py to ensure all strings are unicode strings, and updates the first migration to remove byte strings.

Remove bytestrings from old migrations

---

.travis.yml
tox.ini

Move Travis to xenial, as trusty only has GDAL 1.10, which Django 2.2 drops support for.

Add Django 2.2 testing, drop Django 2.0.

---

mapit/management/command_utils.py
mapit/tests/test_doctests.py

cascaded_union was deprecated in Django 1.10 and has been removed in 2.0.
The current Django requirement is >= 1.11.2 which is still fine.

Use unary_union instead of cascaded_union.

---

mapit_gb/management/commands/mapit_UK_fix_2019-05.py

Fixes https://github.com/mysociety/mapit/issues/341
The output when run without commit is:
```
(.venv) $ python manage.py mapit_UK_fix_2019-05 ~matthew/bl-2018-10/Data/GB/district_borough_unitary_ward_region.shp
Updating area E0501239 to E05012396
Updating area E05012199 to E05012208
Updating area E05006336 to E05012387
Updating area E05010394 to E05012991
Updating area E05009767 to E05012992
Updating area E05002732 to E05011571
Updating area E05010391 to E05012990
Updating area E05005857 to E05011847
Updating area E05005276 to E05012199
Updating area E05009795 to E05012630
Updating area E05005863 to E05011853
Updating area E05005865 to E05011854
Creating new E05002732 (DIW), Stretham Ward
Creating new E05005276 (DIW), Garrison Ward
Creating new E05010394 (DIW), Chartham & Stone Street …
```

[UK] Add script to fix 2019-05 Boundary-Line.

---

mapit_gb/management/commands/mapit_UK_import_soa_2011.py

Creates new import command to import current UK census geography into MapIt.
Mostly adjusting column names, but also a coordinate conversion for NI SOAs.
Sources file urls and example commands: 
https://geoportal.statistics.gov.uk/datasets/lower-layer-super-output-areas-december-2011-full-extent-boundaries-in-england-and-wales
`python manage.py mapit_UK_import_soa_2011 Lower_Layer_Super_Output_Areas_December_2011_Full_Clipped__Boundaries_in_England_and_Wales.shp --type=lsoa --commit`
https://geoportal.statistics.gov.uk/datasets/middle-layer-super-output-areas-december-2011-boundaries-bfe
`python manage.py mapit_UK_import_soa_2011 Middle_Layer_Super_Output_Areas_December_2011_Boundaries_BFE.shp --type=msoa --commit`
https://data.gov.uk/dataset/ab9f1f20-3b7f-4efa-9bd2-239acf63b540/data-zone- …

New import command to deal with post-2011 LSOAs/DZ/SOA

---

mapit_gb/management/commands/mapit_UK_import_local_authority_canon.py

Adds the standardised registry codes for all UK local authorities.
Currently doesn't replace the 'local_authority_eng' - although will be more up to date for eng authorities given 2019 changes.
Source file: https://raw.githubusercontent.com/ajparsons/uk_local_authority_names_and_codes/master/lookup_gss_to_registry.csv
`python manage.py mapit_UK_import_local_authority_canon lookup_gss_to_registry.csv`

Added import for canonical authority codes (across UK)

---

mapit_gb/fixtures/uk.json
mapit_gb/templates/mapit/api/areas-types.html

Creates new import command to import Travel to Work Areas (TTWA) into MapIt.
Sources file urls and example command:
`http://geoportal.statistics.gov.uk/datasets/d3062ec5f03b49a7be631d71586cac8c_0
`
```
python manage.py mapit_UK_import_ttwa Travel_to_Work_Areas_December_2011_Full_Clipped_Boundaries_in_United_Kingdom.shp
--commit
```

Added import command and area type for travel to work areas

---

mapit/management/commands/mapit_import.py

GSS codes in the UK start with E/N/W/S for the constituent country.
Adding support for this makes importing UK-wide datasets easier.
I think this then removes the need for a special TTWA import script.

Add first-letter support to import script.

---

install/index.md

Install instructions adjusted to reflect the packages are stored in the setup.py file rather than requirements.txt and that syncdb is not needed in the current default django version.

Updated install instructions

---

.github/workflows/default.yml
mapit/iterables.py
mapit/management/commands/mapit_import.py
mapit/management/commands/mapit_import_area_unions.py
mapit/middleware/__init__.py
mapit/models.py
mapit/shortcuts.py
mapit/tests/test_admin.py
mapit/tests/test_generation_commands.py
mapit/tests/test_import_commands.py
mapit/tests/test_query_args.py
mapit/views/areas.py
mapit/views/postcodes.py
mapit_gb/management/commands/mapit_UK_add_gss_codes_to_ni_areas.py
mapit_gb/management/commands/mapit_UK_add_names_to_ni_areas.py
mapit_gb/management/commands/mapit_UK_fix_2011-10.py
mapit_gb/management/commands/mapit_UK_fix_2012-05.py
mapit_gb/management/commands/mapit_UK_fix_2013-10.py
mapit_gb/management/commands/mapit_UK_fix_2019-05.py
mapit_gb/management/commands/mapit_UK_import_2011_scotparl.py
mapit_gb/management/commands/mapit_UK_import_boundary_line.py
mapit_gb/management/commands/mapit_UK_import_osni.py
mapit_gb/management/commands/mapit_UK_import_police_force_areas.py
mapit_gb/tests.py
mapit_no/management/commands/mapit_NO_import_osm.py
project/wsgi_monitor.py
setup.py
tox.ini

Minimum python 3 is 3.6 for 3.0.
We need to stop using vendored six, as that has been removed, and the
URL dispatcher has changed so it no longer passes in non-matching parts
(in our case, the format ending).
Hopefully that is all.

Django 3 support

---

mapit/management/find_parents.py
mapit_gb/controls/2020-10.py
mapit_gb/management/commands/mapit_UK_find_parents.py
mapit_gb/tests.py

See #365.
Adds a control file that matches up the GLA area and allows CED/DIW through as new areas if inside a Buckinghamshire UTA.
And allows `find_parents` to accept a UTA parent for a CED/DIW also because of Buckinghamshire.

October 2020 Boundary-Line import

---

mapit_gb/management/commands/mapit_UK_import_boundary_line.py

If you are running on a system with GDAL2.2 or higher, null entries are
now returned as null, not the empty string. Boundary-Line contains null
entries for its NCP areas, so treat those like an empty string.
Fixes #369

[UK] Default blank names to the empty string.

---

mapit/shortcuts.py

This PR modifies the responses for the postcode endpoint to not use a streaming HTTP response, to allow Django to cache the responses preventing the need for subsequent expensive database queries.
Previously, the output_json method always returned a streaming HTTP response, which prevented the need to load the full response contents into memory before sending, lowering memory usage. However, this prevented Django from caching views using the output_json method. This modifies the output_method to not use a streaming response for those responses already loaded into memory (i.e. not using the iterdict) and would gain no benefit. This will allow for Django to automatically cache those views and reduce the need for expensive database queries (e.g. mainly the /postcodes endpoints).

Improve caching of postcode endpoints

---

.github/workflows/default.yml
mapit/views/areas.py
mapit/views/postcodes.py
tox.ini

Some queries on Postgres 13.7 timeout with a different error, so make sure we spot that and handle it nicely.
For https://github.com/mysociety/sysadmin/issues/1568

Handle alternative Postgres timeout errors

---

mapit/middleware/view_error.py

Since Django 2.1, all 500s are logged as errors, including ones manually
generated by the code. We do not want to receive logged errors for ones
we are choosing to generate, so mark the response as already logged with
the logger's internal flag.

Do not log our own ViewExceptions.

---

mapit/models.py
mapit/views/postcodes.py

As per the comment, without doing this the query performs an identical transform on every row it's looking at, rather than doing it once at the start.
Before:
```
mapit=# explain analyze
SELECT * FROM "mapit_postcode"
WHERE ( ST_CoveredBy(location,
ST_Transform((select ST_Collect(polygon) from mapit_geometry
where area_id=2577 group by area_id), 4326)))
LIMIT 1;
QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=45.32..583.67 rows=1 width=43) (actual time=9536.938..9536.941 rows=1 loops=1)
InitPlan 1 (returns $0)
->  GroupAggregate  (cost=0.42..19.91 rows=3 width=36) (actual time=0.980..0.981 rows=1 loops=1)
Group Key: mapit_geometry.area_id
->  Index …
```

Use a materialized CTE for example postcode too.

---

mapit/shortcuts.py
mapit_gb/management/commands/mapit_UK_import_osni.py
mapit_gb/management/structural_changes.py

Following on from b5172f6d, make sure JSON error output is also marked as already logged, as we do not want to receive logged errors for ones we are choosing to generate.

Do not log our own JSON ViewExceptions.

---

CHANGES.txt
mapit/management/commands/mapit_generation_raise_on_current_areas.py
mapit/tests/test_generation_commands.py

Allows selecting multiple countries / types e.g. `--type "ABC" --type "DEF" --country "E" -- country "W"`.
Also allows flipping to exclude by type or country via `--type-mode "all-but" --country-mode "all-but"`.

Add filtering and excluding by mutliple types and countries in raise generation script.

---

mapit/iterables.py
mapit_gb/management/commands/mapit_UK_import_onspd.py

This switches from the default loop/check/save to postgres copy into a temporary table and update/insert based on differences. The first run compared to previous way will have a lot of minute updates due to the location calculation being slightly different (going from CSV E/N -> 4326 in DB rather than code), but in the order of millimetres(!). Import time goes from 12 hours to a few minutes.

Faster ONSPD import

---

mapit_no/bin/mapit_osm_to_kml

Use `api.openstreetmap.org/api/` -and HTTPS- instead of `www.openstreetmap.org/api/*`.
(Is: https://github.com/openstreetmap/operations/issues/951)
cc: @dracos

Switch to api.openstreetmap.org API host

---

bin/site-specific-install.sh
conf/sysvinit.example

This PR attempts to fix the automated installation script for MapIt on more recent versions of Ubuntu (but not Jammy, 22.04) and Debian Linux.
I have confirmed the installation succeeds on clean installs of Ubuntu Focal (20.04) and Debian Bullseye (11) on Amazon EC2 instances at the default hostname, and tested subsequent loading of boundary data works on Debian Bullseye.
It **does not appear to work automatically on Ubuntu Jammy (22.04)** because of changes in `apt-get install` behaviour, I think related to the [`needrestart`](https://askubuntu.com/questions/1367139/apt-get-upgrade-auto-restart-services) command, but I haven't had time to investigate this properly.
To use this version of the install script, you can use the override behaviour in the `install-site.sh` script. Run the …

Fix MapIt install script

---

.github/workflows/default.yml
mapit/views/areas.py
mapit_gb/countries.py
tox.ini

This should mean no unhandled server errors if multiple results returned, and both endpoints should act the same (so the /code lookup will now pass through a query string, and the legacy /area lookup should cope better with multiple results, and you could now include a type to differentiate between WMC/WMCF).

Use standard area_from_code for legacy code lookup

---

.github/workflows/default.yml
mapit/admin.py
mapit/models.py
mapit/views/areas.py
project/settings.py
setup.py
tox.ini

Fixes https://github.com/mysociety/mapit/issues/396

Django 4 changes

---

mapit/add_areas_from_file/core.py

This makes the import command always filter by area type (which is a mandatory argument).
Fixes #429

fix(mapit_import): Filter by area type when looking for existing areas
