mapit/templates/mapit/base.html
This will allow me to add some extra styling for the mapit gb api user
accounts, without having to fork the base template.
=> Add template blocks for extra css and js into base.html

CHANGES.txt, mapit/templates/mapit/base.html, setup.py
I've updated the CHANGES.txt and bumped the version in setup.py, @dracos is
there anything else I need to do before I tag it and release to PyPi?
(Note: I'd like to merge #176 into this too)
=> Proposed version 1.3.1

mapit/djangopatch.py, mapit/templatetags/compat.py, mapit/urls.py, mapit_za/management/commands/mapit_za_import_boundaries.py, project/settings.py, setup.py
=> Make sure CSS is compiled when running setup.py.

mapit/templates/mapit/licensing.html
This is mostly copied from the new text on the TWFY page, along with some
re-arrangements to match the general tone of that such as moving the techy
stuff lower down.
@abimysoc, @MyfanwyNixon - could you check this over too? (I'll add a
screenshot in a second).
Closes #181
=> Add pricing info to the licensing page

mapit/templates/mapit/postcode.html
=> Fix link to geohack tool

mapit_gb/controls/2015-10.py, mapit_gb/management/commands/mapit_UK_import_boundary_line.py
Otherwise you can't import this to a fresh database and get the patch
fixes (as the control file requires previous data).
=> Move October 2015 Boundary-Line patch to main.

mapit_gb/controls/2016-05.py, mapit_gb/management/commands/mapit_UK_import_boundary_line.py
Deal with the Welsh Assembly boundary issues caused by new data being
provided too early, a returning parish council that presumably should
not have been deleted, and a duplicate unit ID.
Fixes #240
=> [UK] May 2016 Boundary-Line import.

mapit/templates/mapit/api/code.html, mapit/templates/mapit/index.html, mapit_gb/templates/mapit/api/code-examples.html, mapit_gb/templates/mapit/api/code-types.html, mapit_global/templates/mapit/api/area-example-related.html, mapit_global/templates/mapit/api/code-examples.html, mapit_global/templates/mapit/api/code-types.html
This has been usable since fd959bcfb in June 2012, but has never been
documented on the front page guide to the API.  This adds such
documentation, with examples and explanation of the code types for
the UK and Global.
=> Add documentation for the /code API endpoint

mapit/geometryserialiser.py, mapit/management/commands/mapit_import.py, mapit/management/commands/mapit_import_area_unions.py, mapit/tests/test_views.py, mapit/views/areas.py, mapit_gb/management/commands/mapit_UK_ni_consolidate_boundaries.py, mapit_gb/management/commands/mapit_UK_time_lookups.py, mapit_global/management/commands/mapit_global_find_differences.py, mapit_global/management/commands/mapit_global_import.py, mapit_global/management/commands/mapit_global_oneoff_fix_gen4.py, project/wsgi_monitor.py
Tweak/add couple of tests to show that these functions were still being called, and stop using them.
=> Fix use of old Django aggregate functions

CHANGES.txt, mapit/management/commands/mapit_delete_areas_from_new_generation.py, mapit/management/commands/mapit_generation_deactivate.py, mapit_gb/management/commands/mapit_UK_import_codepoint.py, mapit_gb/management/commands/mapit_UK_import_nspd_ni.py, mapit_gb/management/commands/mapit_UK_import_onspd.py, mapit_gb/management/commands/mapit_UK_time_lookups.py, mapit_gb/management/commands/mapit_UK_update_ons_ids.py, mapit_gb/management/commands/mapit_UK_update_ons_ids2.py, mapit_no/management/commands/mapit_NO_import_bolstad_postcodes.py, setup.py
Finish fixing the thing started in 1.5.3.
=> Version 1.5.4 

mapit/tests/test_views.py, mapit/views/postcodes.py
=> Fix redirect notation for Django 1.10+

.travis.yml, CHANGES.txt, mapit/geometryserialiser.py, mapit/middleware/__init__.py, mapit/middleware/view_error.py, mapit/models.py, mapit/tests/test_admin.py, mapit/tests/test_middleware.py, mapit/views/areas.py, mapit/views/postcodes.py, mapit_gb/controls/2016-05.py, mapit_gb/countries.py, mapit_gb/management/commands/mapit_UK_add_2016_forward_dated_codes.py, mapit_gb/management/commands/mapit_UK_scilly.py, project/settings.py, project/urls.py, setup.py, tox.ini
=> Version 2.0 release

mapit/models.py, mapit_gb/management/commands/mapit_UK_import_onspd.py
=> ONSPD February 2018 adds two cols before co-ords.

mapit_gb/controls/2018-05.py
~~All CEDs are all duplicated. This feels like a waste, none has had boundary changes~~ My mistake in test import.
=> First stab at 2018-05 control file.

mapit/templates/mapit/api/areas.html, mapit/tests/test_views.py, mapit/urls.py, mapit/views/areas.py
=> Add endpoints for children and areas by type geodata

mapit/admin.py
This has been removed from 2.0 - https://docs.djangoproject.com/en/2.2/internals/deprecation/#deprecation-removed-in-2-0
=> Fix allow_tags

mapit_gb/controls/2019-05.py, mapit_gb/management/commands/mapit_UK_import_boundary_line.py
(this is already live)
Essex is missing so needs generation updating manually :-/
=> [UK] May 2019 Boundary-Line import.

mapit_gb/management/commands/mapit_UK_add_2020_structural_changes.py
This script is to be run at the start of April to create the new Buckinghamshire Council and its new wards.
=> [UK] Script for 2020 England council changes.

mapit/templates/mapit/footer.html, mapit_it/templates/mapit/footer.html
Updates the footer wording, where found. Does this result in both global.mapit and international.mapit getting the new wording and if not, what else needs changing?
=> Company name change

.github/workflows/default.yml, mapit_gb/management/commands/mapit_UK_add_2020_structural_changes.py, mapit_gb/management/commands/mapit_UK_add_2021_structural_changes.py, mapit_gb/management/structural_changes.py, mapit_gb/templates/mapit/api/areas-types.html, mapit_gb/templates/mapit/api/postcode-example.html, tox.ini
No need to worry about which council wards go to which unitary council, as find_parents will sort that for us.
For the change of Northamptonshire from county + 7 districts to 2 unitaries on 1st April 2021.
Also fixes https://github.com/mysociety/mapit.mysociety.org/issues/65
=> [UK] Script for 2021 England council changes.

conf/general.yml-example, mapit/context_processors.py, mapit/management/commands/mapit_delete_areas_from_new_generation.py, mapit/management/commands/mapit_generation_activate.py, mapit/management/commands/mapit_generation_create.py, mapit/management/commands/mapit_generation_deactivate.py, mapit/templates/mapit/api/point.html, mapit/tests/test_generation_commands.py, mapit/tests/test_views.py, mapit/views/areas.py, project/settings.py
=> Add within parameter to point lookup.

mapit_gb/controls/2021-05.py, mapit_gb/management/commands/mapit_UK_add_2020_structural_changes.py, mapit_gb/management/commands/mapit_UK_add_2021_structural_changes.py, mapit_gb/management/commands/mapit_UK_import_boundary_line.py, mapit_gb/management/structural_changes.py
Control file is hopefully not actually needed, is same as first-gss.
Also includes fixes to Northamptonshire script that I thought I had PRed already, but apparently not.
=> [UK] May 2021 boundary changes

mapit_gb/controls/2021-10.py, mapit_gb/countries.py, mapit_gb/fixtures/uk.json, mapit_gb/management/commands/mapit_UK_import_ncps.py, mapit_gb/templates/mapit/api/areas-types.html, project/settings.py
Also includes fix for version 6 of PyYAML.
The mapping CSV file is this one: https://geoportal.statistics.gov.uk/documents/ons::non-civil-parished-areas-april-2021-names-and-codes-in-england
=> [UK] 2021 October Boundary-Line (including ERs), and NCP import script

mapit_gb/controls/2022-05.py, mapit_gb/management/commands/mapit_UK_import_boundary_line.py
A couple of parishes back from the dead, and an incorrect ward code.
=> [UK] May 2022 Boundary-Line import.

mapit_gb/management/commands/mapit_UK_import_boundary_line.py
=> [UK] Deal with Senedd code rename.

mapit_gb/management/commands/mapit_UK_add_gss_codes_to_ced_areas.py
Current data from ONS: https://geoportal.statistics.gov.uk/documents/ons::county-electoral-division-to-county-may-2021-lookup-for-england/about (needs converting to CSV manually, didn't really want to introduce a dependency for parsing XLSX files)
=> [UK] Add command to add GSS codes to CED areas using CSV from ONS

mapit/models.py
In PostgreSQL 12, the default behaviour is to inline basic CTEs such as
this one, which in this case decreases the performance of the query.
=> Specify the CTE should be materialized.

mapit/shortcuts.py, project/settings.py
Mirroring https://github.com/mysociety/mapit.mysociety.org/pull/142.
=> Migrate from python-memcached to pylibmc.

mapit_gb/controls/2023-10.py, mapit_gb/management/commands/mapit_UK_fix_2023-05.py
Control file and one off script to deal with issues caused by errors in the previous release.
=> [UK] October 2023 Boundary-Line import.

CHANGES.txt, mapit/models.py, mapit/templates/mapit/api/area.html, mapit/templates/mapit/api/areas.html, mapit/templates/mapit/api/point.html, mapit/templates/mapit/api/postcode.html, mapit/tests/test_query_args.py, mapit/views/areas.py, mapit/views/postcodes.py
Fixes https://github.com/mysociety/societyworks/issues/4162
=> Add max_generation parameter.

mapit_gb/controls/2025-05.py, mapit_gb/management/commands/mapit_UK_2025_update_nie.py, mapit_gb/management/commands/mapit_UK_import_boundary_line.py
* Ignores incorrect boundary change between Maidstone Rural West and Maidstone Central 
* Ignores incorrect name change of Tewkesbury Borough Council
* Updates Barnsley/Sheffield boundary of existing MTD IDs
* Notes which CTYs are having boundary changes (as we can't use GSS codes as they don't have them)
* Includes NIE update script from 2024 general election.
=> [UK] May 2025 Boundary-Line import.
